### ISSUE TITLE
Plotting bug

### ISSUE THREAD

**Issue by Samwalton9** [jmackereth/eaglestuff#13]
There's a plotting bug (present in your most recent version, not sure when it was added), whereby the line `hist = [float(histo)/float(sum(hist)) for histo in hist]` errors due to dividing by zero. This occured with halo 70, but doesn't with 72 (the only two I've checked).

This seems to only effect the plotting (doesn't occur otherwise), but could be indicative of underlying issues. It takes a couple of runthroughs to error on 70 (I can plot two lots of hist from a few lines up before it errors), so I suspect it might be something like there not being any particles in a particular radius bin or something.

**Comment by jmackereth** [comment]
The problem is when a bin has no stars. Fof 70 and 72 in the 25 Mpc run will indeed have no stars in those bins as they will be tiny, right?

I don't think it is an underlying problem. I'm worrying that the code is maybe getting a bit complex though, we can talk about this next week. I definitely need to refactor the plot bit into something else or remove it entirely, as presumably you won't need those plots?

**Comment by Samwalton9** [comment]
I'm wary of it getting too complex but I think the saving and loading will speed things up tremendously; it loads the files instantly as opposed to needing to go through every step. It may limit flexibility though, and I have some thoughts on that we should discuss!

Ah yes of course, I forgot I'd switched to the 25Mpc run, that makes sense. Yeah I guess stuff like person specific plotting should be done outside this code.

Sam

On 22/01/2016 18:59, Ted Mackereth wrote:
The problem is when a bin has no stars. Fof 70 and 72 in the 25 Mpc run will indeed have no stars in those bins as they will be tiny, right?

I don't think it is an underlying problem. I'm worrying that the code is maybe getting a bit complex though, we can talk about this next week. I definitely need to refactor the plot bit into something else or remove it entirely, as presumably you won't need those plots?

> On 22 Jan 2016, at 15:15, Sam Walton notifications@github.commailto:notifications@github.com wrote:
> 
> There's a plotting bug (present in your most recent version, not sure when it was added), whereby the line hist = [float(histo)/float(sum(hist)) for histo in hist] errors due to dividing by zero. This occured with halo 70, but doesn't with 72 (the only two I've checked).
> 
> This seems to only effect the plotting (doesn't occur otherwise), but could be indicative of underlying issues. It takes a couple of runthroughs to error on 70 (I can plot two lots of hist from a few lines up before it errors), so I suspect it might be something like there not being any particles in a particular radius bin or something.
> 
> —
> Reply to this email directly or view it on GitHub.

—
Reply to this email directly or view it on GitHubhttps://github.com/jmackereth/eaglestuff/issues/13#issuecomment-174012529.

## 

Phd Student
Astrophysics Research Institute, LJMU
S.R.Walton@2011.ljmu.ac.ukmailto:S.R.Walton@2011.ljmu.ac.uk

---

Important Notice: the information in this email and any attachments is for the sole use of the intended recipient(s). If you are not an intended recipient, or a person responsible for delivering it to an intended recipient, you should delete it from your system immediately without disclosing its contents elsewhere and advise the sender by returning the email or by telephoning a number contained in the body of the email. No responsibility is accepted for loss or damage arising from viruses or changes made to this message after it was sent. The views contained in this email are those of the author and not necessarily those of Liverpool John Moores University.
